### ISSUE TITLE
Investigate SSR support

### ISSUE THREAD

**Issue by wmangimelli** [Headstorm/foundry-ui#128]
When using Foundry with server-side rendering (SSR) apps, i.e. apps created with NextJS, don't have a window object and will require polyfilling.

AC:
* Test out Foundry UI in a NextJS application
* Find a solution to get it working (Google is your friend)

**Comment by aVileBroker** [comment]
I wonder if it is styled-components not working - they have a page dedicated to enabling server-side rendering: https://styled-components.com/docs/tooling#serverside-rendering

**Comment by aVileBroker** [comment]
A simple `create-next-app` would be a good place to start testing solutions.
