### ISSUE TITLE
Ensure storybook is not included in the installed bundle

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#181]
Currently it is being included in consuming apps' node_modules

AC:
- [ ] ensure it is not included in consuming apps' node_modules

From @jakeoien:

> This ticket was intending to solve an issue where linking Foundry in a local project causes multiple versions of React to load. We came up with this as the solution. Turns out, this isn’t enough - we’re still seeing the issue even after this change. The problem we’re running into is that these storybook dependencies are a part of the foundry package itself.
> 
> I’m wondering if a better way of going about this would be to move all of the storybook stuff out of our src/ directory so that it’s not actually a part of our bundled code.
> 
> The big thing this blocks is trying to make changes like bugfixes using a local version of foundry, that currently won’t work.

From me:
> I’ve seen packages (@react-three/drei for instance) that put all the storybook stuff in .storybook - which may solve the issue for us.

**Comment by shaw-matt** [comment]
Moved to 'done' but still open
