### ISSUE TITLE
TextInput CharacterCounter is not style-able or ref-able through the API

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#206]
You can use the ErrorContainer as an example of how to set up the CharacterCount properly.

Also - the character count is quite far away from the input - I would suggest making it a smaller gap. To do so, change the `top` style to

```css
top: calc(100% + 0.25em);
```

AC:

- Rename CharacterCounter to CharacterCount (non breaking change)
- Add CharacterCount to the TextInput module export
- Add a prop to the TextInput API for StyledCharacterCount
- Add a ref to the CharacterCount and add it to the props
- Add a props object to the CharacterCount and add it to the props

**Comment by n-wes** [comment]
Currently working on this

**Comment by aVileBroker** [comment]
Updated the description to include a slight style change @n-wes
