### ISSUE TITLE
Table | Does not support footers

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#207]
User story:
> As a user of the Table component I want to be able to specify a footer through the API, separate from the `data` array.

Dev hint
> This could be done in the `column` prop (adding a `footer`property to the column object to define what string/number will be displayed there) or in a separate prop from `column` or `data` simply called `footer`. The latter would mean the column definitions could be more static and only `data` and `footer` would be likely to depend on dynamic data.

Requirements:
* Accept data for a footer row which has the same typing as the normal cell rows. It should accept new overrides for the new subcomponents.
* New `footer` data should go into the tfoot DOM element to keep it as accessible as possible.
* It should conditionally render the `tfoot` depending on if any data is being rendered in it.
* It should adhere to the responsiveness that exists in the rest of the `Table` component.
* Tests should be updated if necessary to cover the new code additions.

Design:
The FooterRow and FooterCell can be restyled Row/Cell styled components, but should use grayXLight for the background and set the font-weight to 700.
![image](https://user-images.githubusercontent.com/7891559/108270100-93646380-7134-11eb-8330-20b9526e3fe1.png)

This shouldn't be a breaking change.

**Comment by j-storey5** [comment]
Started 8/5/21
