### ISSUE TITLE
Modal | Pressing Escape should call the onCloseOutside function

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#208]
For better accessibility, having keyboard controls beyond tabbing to the close X button is very important.

Include a unit test and/or jest-axe test to ensure this functionality isn't broken in a future update.

**Comment by ifarazkhalid** [comment]
I'll try to work on this ticket! Should get me started with setting up and get going with React. First time ever working with React so this might be a little more than 0.5 story points for me.

**Comment by davisharlan** [comment]
Closing since this has already been done.
