### ISSUE TITLE
Dropdown | Keyboard controls aren't correct

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#210]
Current: Currently, pressing tab focuses the dropdown, then pressing tab again opens the options, and then again steps through the options, then leaves the dropdown without closing it.

Expected: Tabbing should continue focusing the dropdown, but pressing it again should move to the next form control. Only pressing up/down/enter should open the dropdown, and only up/down should move through the option list. Once the focus has left the dropdown, it should close automatically.

**Comment by etallion** [comment]
@ericbaumann  I don't have permission to assign to myself. Can you assign this task to me, please?
