### ISSUE TITLE
Text | Children type is too limited for common usage

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#213]
Text's children prop is currently:
`children?: string | Node;` which accepts string, Node, and undefined.

This doesn't allow for multiple children, or even normal jsx being passed in.
```
This JSX tag's 'children' prop expects a single child of type 'string | Node | undefined', but multiple children were provided.  TS2746
  > 34 | <Text>Hello my name is {customerName}</Text>
       |  ^
```

It also doesn't allow for regular nested JSX (JSX.Element) or Element
```
Type 'Element' is not assignable to type 'string | Node | undefined'.
```

AC
> Update the children type for Text to be more flexible

> Bonus: Create a generic "let me pass jsx stuff here" type we can reuse throughout Foundry UI, and include it in the `src/components/commonTypes.ts` file.

**Comment by twelvetosix** [comment]
I'll take this. Warning I am a complete React n00b
