### ISSUE TITLE
Interaction feedback story example should be full-screen

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#219]
Currently the interaction feedback story in storybook is just a basic button, and for some reason also isn't very performant (compare InteractionFeedback/Button with the Dropdown story)

AC:

- Create a full-screen experience for the InteractionFeedback story
- Add text in the center of the screen which says "Click anywhere!"
- Ensure it is performant

**Comment by jjrockhill** [comment]
@aVileBroker This is a two parter but I looked over the performance issue and your parsefloats will always cause headaches when animating SVGs. Adding this `defaultInterpolationFunctions` will significantly increase the performance of the animations:

```
const defaultInterpolationFunctions = {
  r: (r: any) => r.to((val: string) => `${Math.abs(parseFloat(val).toFixed(1))}`),
  opacity: (opacity: any) => opacity.to((val: string) => `${parseFloat(val).toFixed(1)}`),
};
```

**Comment by aVileBroker** [comment]
Love it! Hit me with a PR if you get the chance.
