### ISSUE TITLE
Dropdown | Missing bottom border when open can affect page layout in (default) outline variant

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#223]
Currently, when opening an 1outline1 variant dropdown, the bottom border is set to `0` width and `transparent` color to look flush with the options container. This ends up jiggling the layout as its dimensions are changing as a result. We should only change the color of the bottom border to transparent and move the options container up by the width of the new transparent border.

AC:

- Opening/closing the dropdown does not change its dimensions and move items below it

**Comment by ben-douthit** [comment]
I can try to take this one if it's available.
