### ISSUE TITLE
Card | Interaction feedback splash isn't contained to card when elevation = 0

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#233]
It's not just the visual component either - the clickable area extends to the ENTIRE screen capturing all clicks. This isn't quite an edge case, but WILL break sites which use elevation 0.

Elevation 0
![image](https://user-images.githubusercontent.com/7891559/123372810-e0749e00-d549-11eb-95fc-dd3486ba0a19.png)

Default elevation
![image](https://user-images.githubusercontent.com/7891559/123372847-f2564100-d549-11eb-8809-c76914314e3a.png)

**Comment by dawsonbooth** [comment]
Worth noting this is the case when elevation < 0 as well. I've tracked it down to the `getBoundingClientRect` function which mysteriously returns different values depending on the element's elevation.

Here's the return value for `getBoundingClientRect` on an example Card component when elevation > 0:
![Screen Shot 2021-06-28 at 12 12 10 PM](https://user-images.githubusercontent.com/10625031/123676971-2e1f2e00-d80a-11eb-8445-47b60a3b1691.png)
elevation <= 0:
![Screen Shot 2021-06-28 at 12 11 47 PM](https://user-images.githubusercontent.com/10625031/123676997-35ded280-d80a-11eb-991c-14725878c3c6.png)
