### ISSUE TITLE
EsLint | Files are not getting linted on macOS

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#275]
Here is a thread which describes the issue: https://github.com/eslint/eslint/issues/13118#issuecomment-605724101

on windows, our current command `"lint-ci": "yarn run prettier:write && eslint src/**/*.tsx src/**/*.ts --ignore-pattern *.css --quiet"` works, but on macOS only `"lint-ci": "yarn run prettier:write && eslint './src/**/*.tsx' './src/**/*.ts' --ignore-pattern *.css --quiet"` works to find lint errors.

**Comment by dawsonbooth** [comment]
https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784
