### ISSUE TITLE
Marketing site | Fix github coverage path, and fix issue causing a blank page bug

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#286]
- [ ] Fix the coverage table GET path to match new project structure
- [ ] Fix the issue causing the issue (something.length doesn't exist) causing a blank page
- [ ] Add an error boundary around the github fetch/render to keep similar issues from breaking the page in the future

**Comment by shaw-matt** [comment]
Moved to 'done' but still open
