### ISSUE TITLE
CutoutUnderlay component

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#301]
CutoutUnderlay is not a mandatory name - feel free to come up with something better!

> As a developer I want to be able to highlight an element on the UI given only it's ref. The shape of the highlight should either be circular or rectangular (if rectangular it should match the aspect ratio of the target element's bounds)

Suggested API:

- [x] `children` - accepts children and renders them with no additional styling
- [x]  `targetElementRef `- this is the item that will be highlighted
- [x]  `backgroundDarkness` - same as Modal
- [x]  `backgroundBlur` - same as Modal (if the backdrop-filter doesn't work, roll your own svg filter)
- [x]  `shape` - enum either `circle`, `box`, `rounded-box` - will dictate the svg path generated inside
- [x]  `padding` - probably should be a pixel number - adds some padding between the cutout and the element
- [x]  `onClick` - allows "onClickOutside" type behavior in the Walkthrough component.
- [x]  `animateTargetChanges` - if true, the cutout moves/grows to new target using react-spring
- [x]  all the subcomponent/props/ref that is common in all foundry components
- [x]  props for customizing the animation of `animateTargetChanges`

- [x] spotlight the targeted element
- [x] animate from circle/square/rounded
- [ ] close spotlight when no target exists

DevTip: if the cutout isn't "cutting out" the underlay, change [the fill-rule](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule) to `evenodd` or another option.

Much like the Modal - this should render in a portal. Theoretically this could use the Modal component under the hood and pass an svg to the StyledUnderlay subcomponent, but then we'd get all the animated stuff which I don't think we need.

Cutout image example:
![image](https://user-images.githubusercontent.com/7891559/130661104-acfc043f-3705-450f-bff3-df8c587e851b.png)

Final walkthrough component:
![image](https://user-images.githubusercontent.com/7891559/130661027-82541b9a-3996-479a-a899-f86138f92909.png)

**Comment by shaw-matt** [comment]
Moved to 'done' but still open
