### ISSUE TITLE
Storybook | Update Form Example so the "State" dropdown is searchable

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#306]
Should be as simple as adding the `searchable` prop on the Dropdown, but test it to make sure it works as expected none-the-less.

**Comment by davisharlan** [comment]
@aVileBroker I think this might already be complete. I'll let you close if this is true.

[Place in code](https://github.com/Headstorm/foundry-ui/blob/master/src/components/Dropdown/Dropdown.stories.tsx#L64) and screen shot below.

<img width="1463" alt="Screen Shot 2021-09-03 at 11 44 40 AM" src="https://user-images.githubusercontent.com/35711200/132040432-4ce78f71-44c7-485c-9434-6abed0e622f6.png">
