### ISSUE TITLE
Types | StyledSubcomponentType is too rigid and complains about regular JSX

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#379]
The intent behind the architecture is to allow any JSX to be passed into those `Styled_________` props. While we encourage restyling our internal base components with styled-components - we shouldn't complain if the developer doesn't do that, as flexibility is the selling-point of Foundry UI.

In the StyledSubcomponentType type, I would try to union the current type with `JSX.Element`.

**Comment by akrabdev** [comment]
can take this one, feel free to assign

**Comment by akrabdev** [comment]
Experimented a bit and I found the following

Union  StyledSubcomponentType with `JSX.Element` : 
```ts
export type StyledSubcomponentType =
  | (string & StyledComponentBase<any, SubcomponentPropsType>)
  | JSX.Element;
 ```
 
causes error at https://github.com/Headstorm/foundry-ui/blob/19dada4c5f97de6346a97d68578b0392c808095f/src/context/index.tsx#L118 
 as `styled` expects type: `AnyStyledComponent`

Currently not sure how to deal with this, maybe I misinterpreted the requirement too.
