### ISSUE TITLE
Button | Change -webkit-appearance to none to fix button anchors on Safari

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#405]
For buttons with the `as` prop for the container changing it from a `button` to an `a`, keeps the role as `button` as expected, but safari forces button appearance to the anchor because of that role.

Fix is to set `-webkit-appearance: none;` on all button containers (we'll always want our styles)

Safari:
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/7891559/176947155-5cca1ff6-5115-418e-b163-f1a460fdf3ef.png">

Chrome
![image](https://user-images.githubusercontent.com/7891559/176947174-5f9d44d2-621c-4d66-b11a-37f2ecb2e906.png)

**Comment by asheerrizvi** [comment]
@aVileBroker have opened a PR for this, lmk if this is ok?

#406
