### ISSUE TITLE
Card ripple leaving its container in safari

### ISSUE THREAD

**Issue by GriseldaZBalmaceda** [Headstorm/foundry-ui#408]
The ripple effect in safari is going outside of the container and causing a an infinite amount of ripples to be created

**Comment by aVileBroker** [comment]
Hmm seems similar to [this issue from a while back](https://github.com/Headstorm/foundry-ui/issues/233), but I also remember there being some fill-type css rule that also addressed this. @dawsonbooth do you know what I'm talking about?

**Comment by dawsonbooth** [comment]
The `contain` property might be what we're looking for: https://developer.mozilla.org/en-US/docs/Web/CSS/contain
