### ISSUE TITLE
Table | Various fixes to support HS Constellation

### ISSUE THREAD

**Issue by meghanainaganti** [Headstorm/foundry-ui#434]
**Acceptance Criteria**
- Move responsive title out of cell
- Add styled responsive title (and other api)
- Ensure no title if name is undefined
- Responsive-view transitions don't work - only works on first render

**Comment by xavierdonnellon** [comment]
Gameplan:
1. Move ResponsiveTitle to be sitting next to the CellComponent (so it is rendered even if the cellComponent is overridden).
2. Only show ResponsiveTitle if column name is not empty. 
3. add StyledResponsiveTitle parameter to Table, as well as responsiveTitleProps.
