### ISSUE TITLE
Avatar Component

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#437]
As a user of FoundryUI, I want a component that is able to show an image in a circle/squircle/square/etc. It should show initials in place of my profile photo if it isn't passed in.

### AC:

* New Avatar component
* Includes states for
  * has image url
  * loading
  * error
  * no image url
* Has a variable size
* User Initials, padding, border, etc. scale with the size of the component

>Consistent look/feel/interaction across browsers
>0 A11y violations
>90%+ code coverage
>Storybook knobs, actions, and docs where appropriate
>Responsive

**Comment by shuvrojit** [comment]
Assign it to me.
